server:
  port: ${SERVER_PORT_CHECKER:8080}
  servlet:
    encoding:
      charset: UTF-8
  error:
    include-stacktrace: never
    include-binding-errors: never
    include-message: never

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
  api-docs:
    path: /docs

spring:
  messages:
    encoding: UTF-8
    basename: messages/messages
  application:
    name: checker